phrase:
  access_token: 029252c6c2d8fc43878a91bb989bc3da706c3de75ad99d88c4b0a5c34818fc99
  project_id: 92820f0796d8dfdf4b3caa9ded21d30b
  push:
    sources:
    - file: ./<locale_name>.JSON
      params:
        file_format: JSON
  pull:
    targets:
    - file: ./<locale_name>.JSON
      params:
        file_format: JSON
