phrase:
  access_token: 2542ccdb9c2d4f7e462cf376af3cd8ad66ded4a0a7ab53207dd113721b58e27c
  project_id: 1a1ce4ce3ba3e9dffb832ac3a7ad7acd
  push:
    sources:
    - file: components/email/locales/strings.<locale_name>.arb
      params:
        file_format: arb
  pull:
    targets:
    - file: components/email/locales/strings.<locale_name>.arb
      params:
        file_format: arb
